# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/WzyNoEmo/Desktop/hdmi_test_v3/hdmi_test.srcs/sources_1/bd/BD/ip/BD_processing_system7_0_0/BD_processing_system7_0_0.xci
# IP: The module: 'BD_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/WzyNoEmo/Desktop/hdmi_test_v3/hdmi_test.srcs/sources_1/bd/BD/ip/BD_processing_system7_0_0/BD_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'BD_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/WzyNoEmo/Desktop/hdmi_test_v3/hdmi_test.srcs/sources_1/bd/BD/ip/BD_processing_system7_0_0/BD_processing_system7_0_0.xci
# IP: The module: 'BD_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/WzyNoEmo/Desktop/hdmi_test_v3/hdmi_test.srcs/sources_1/bd/BD/ip/BD_processing_system7_0_0/BD_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'BD_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
