# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/BD_axi_smc_0.xci
# IP: The module: 'BD_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/bd_5c0d.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_10/bd_5c0d_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_16/bd_5c0d_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_20/bd_5c0d_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_26/bd_5c0d_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_21/bd_5c0d_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_22/bd_5c0d_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_23/bd_5c0d_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_24/bd_5c0d_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_25/bd_5c0d_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_17/bd_5c0d_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_18/bd_5c0d_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_19/bd_5c0d_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_13/bd_5c0d_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_14/bd_5c0d_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_15/bd_5c0d_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_11/bd_5c0d_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_12/bd_5c0d_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_7/bd_5c0d_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_8/bd_5c0d_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_9/bd_5c0d_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_2/bd_5c0d_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_3/bd_5c0d_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_4/bd_5c0d_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_5/bd_5c0d_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_6/bd_5c0d_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_0/bd_5c0d_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_1/bd_5c0d_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BD_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_10/bd_5c0d_s00a2s_0_ooc.xdc

# XDC: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_16/bd_5c0d_s01a2s_0_ooc.xdc

# XDC: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_20/bd_5c0d_m00s2a_0_ooc.xdc

# XDC: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_21/bd_5c0d_m00arn_0_ooc.xdc

# XDC: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_22/bd_5c0d_m00rn_0_ooc.xdc

# XDC: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_23/bd_5c0d_m00awn_0_ooc.xdc

# XDC: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_24/bd_5c0d_m00wn_0_ooc.xdc

# XDC: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_25/bd_5c0d_m00bn_0_ooc.xdc

# XDC: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_17/bd_5c0d_sawn_0_ooc.xdc

# XDC: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_18/bd_5c0d_swn_0_ooc.xdc

# XDC: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_19/bd_5c0d_sbn_0_ooc.xdc

# XDC: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_11/bd_5c0d_sarn_0_ooc.xdc

# XDC: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_12/bd_5c0d_srn_0_ooc.xdc

# XDC: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_2/bd_5c0d_arsw_0_ooc.xdc

# XDC: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_3/bd_5c0d_rsw_0_ooc.xdc

# XDC: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_4/bd_5c0d_awsw_0_ooc.xdc

# XDC: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_5/bd_5c0d_wsw_0_ooc.xdc

# XDC: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_6/bd_5c0d_bsw_0_ooc.xdc

# XDC: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_1/bd_5c0d_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_1/bd_5c0d_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# IP: C:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/BD_axi_smc_0.xci
# IP: The module: 'BD_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/bd_5c0d.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_10/bd_5c0d_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_16/bd_5c0d_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_20/bd_5c0d_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_26/bd_5c0d_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_21/bd_5c0d_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_22/bd_5c0d_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_23/bd_5c0d_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_24/bd_5c0d_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_25/bd_5c0d_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_17/bd_5c0d_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_18/bd_5c0d_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_19/bd_5c0d_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_13/bd_5c0d_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_14/bd_5c0d_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_15/bd_5c0d_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_11/bd_5c0d_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_12/bd_5c0d_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_7/bd_5c0d_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_8/bd_5c0d_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_9/bd_5c0d_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_2/bd_5c0d_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_3/bd_5c0d_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_4/bd_5c0d_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_5/bd_5c0d_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_6/bd_5c0d_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_0/bd_5c0d_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_1/bd_5c0d_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BD_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_10/bd_5c0d_s00a2s_0_ooc.xdc

# XDC: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_16/bd_5c0d_s01a2s_0_ooc.xdc

# XDC: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_20/bd_5c0d_m00s2a_0_ooc.xdc

# XDC: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_21/bd_5c0d_m00arn_0_ooc.xdc

# XDC: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_22/bd_5c0d_m00rn_0_ooc.xdc

# XDC: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_23/bd_5c0d_m00awn_0_ooc.xdc

# XDC: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_24/bd_5c0d_m00wn_0_ooc.xdc

# XDC: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_25/bd_5c0d_m00bn_0_ooc.xdc

# XDC: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_17/bd_5c0d_sawn_0_ooc.xdc

# XDC: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_18/bd_5c0d_swn_0_ooc.xdc

# XDC: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_19/bd_5c0d_sbn_0_ooc.xdc

# XDC: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_11/bd_5c0d_sarn_0_ooc.xdc

# XDC: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_12/bd_5c0d_srn_0_ooc.xdc

# XDC: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_2/bd_5c0d_arsw_0_ooc.xdc

# XDC: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_3/bd_5c0d_rsw_0_ooc.xdc

# XDC: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_4/bd_5c0d_awsw_0_ooc.xdc

# XDC: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_5/bd_5c0d_wsw_0_ooc.xdc

# XDC: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_6/bd_5c0d_bsw_0_ooc.xdc

# XDC: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_1/bd_5c0d_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/WzyNoEmo/Desktop/hdmi_test/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_1/bd_5c0d_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.
