# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/WzyNoEmo/Desktop/hdmi_test_v3/hdmi_test.cache/wt [current_project]
set_property parent.project_path C:/Users/WzyNoEmo/Desktop/hdmi_test_v3/hdmi_test.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part www.digilentinc.com:pynq-z1:part0:1.0 [current_project]
set_property ip_repo_paths {
  c:/Users/WzyNoEmo/Desktop/vivado-library/ip
  c:/Users/WzyNoEmo/Desktop/my_ip
} [current_project]
set_property ip_output_repo c:/Users/WzyNoEmo/Desktop/hdmi_test_v3/hdmi_test.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib C:/Users/WzyNoEmo/Desktop/hdmi_test_v3/hdmi_test.srcs/sources_1/bd/BD/hdl/BD_wrapper.v
add_files C:/Users/WzyNoEmo/Desktop/hdmi_test_v3/hdmi_test.srcs/sources_1/bd/BD/BD.bd
set_property used_in_implementation false [get_files -all c:/Users/WzyNoEmo/Desktop/hdmi_test_v3/hdmi_test.srcs/sources_1/bd/BD/ip/BD_processing_system7_0_0/BD_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/WzyNoEmo/Desktop/hdmi_test_v3/hdmi_test.srcs/sources_1/bd/BD/ip/BD_clk_wiz_0_0/BD_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/WzyNoEmo/Desktop/hdmi_test_v3/hdmi_test.srcs/sources_1/bd/BD/ip/BD_clk_wiz_0_0/BD_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/WzyNoEmo/Desktop/hdmi_test_v3/hdmi_test.srcs/sources_1/bd/BD/ip/BD_clk_wiz_0_0/BD_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/WzyNoEmo/Desktop/hdmi_test_v3/hdmi_test.srcs/sources_1/bd/BD/ip/BD_rgb2dvi_0_0/src/rgb2dvi.xdc]
set_property used_in_implementation false [get_files -all c:/Users/WzyNoEmo/Desktop/hdmi_test_v3/hdmi_test.srcs/sources_1/bd/BD/ip/BD_rgb2dvi_0_0/src/rgb2dvi_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/WzyNoEmo/Desktop/hdmi_test_v3/hdmi_test.srcs/sources_1/bd/BD/ip/BD_rgb2dvi_0_0/src/rgb2dvi_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/WzyNoEmo/Desktop/hdmi_test_v3/hdmi_test.srcs/sources_1/bd/BD/ip/BD_rst_ps7_0_100M_0/BD_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/WzyNoEmo/Desktop/hdmi_test_v3/hdmi_test.srcs/sources_1/bd/BD/ip/BD_rst_ps7_0_100M_0/BD_rst_ps7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/WzyNoEmo/Desktop/hdmi_test_v3/hdmi_test.srcs/sources_1/bd/BD/ip/BD_rst_ps7_0_100M_0/BD_rst_ps7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/WzyNoEmo/Desktop/hdmi_test_v3/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_vdma_0_0/BD_axi_vdma_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/WzyNoEmo/Desktop/hdmi_test_v3/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_vdma_0_0/BD_axi_vdma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/WzyNoEmo/Desktop/hdmi_test_v3/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_vdma_0_0/BD_axi_vdma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/WzyNoEmo/Desktop/hdmi_test_v3/hdmi_test.srcs/sources_1/bd/BD/ip/BD_v_axi4s_vid_out_0_0/BD_v_axi4s_vid_out_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/WzyNoEmo/Desktop/hdmi_test_v3/hdmi_test.srcs/sources_1/bd/BD/ip/BD_v_axi4s_vid_out_0_0/BD_v_axi4s_vid_out_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/WzyNoEmo/Desktop/hdmi_test_v3/hdmi_test.srcs/sources_1/bd/BD/ip/BD_v_tc_0_0/BD_v_tc_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/WzyNoEmo/Desktop/hdmi_test_v3/hdmi_test.srcs/sources_1/bd/BD/ip/BD_v_tc_0_0/BD_v_tc_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/WzyNoEmo/Desktop/hdmi_test_v3/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_10/bd_5c0d_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/WzyNoEmo/Desktop/hdmi_test_v3/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_16/bd_5c0d_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/WzyNoEmo/Desktop/hdmi_test_v3/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_20/bd_5c0d_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/WzyNoEmo/Desktop/hdmi_test_v3/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_21/bd_5c0d_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/WzyNoEmo/Desktop/hdmi_test_v3/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_22/bd_5c0d_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/WzyNoEmo/Desktop/hdmi_test_v3/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_23/bd_5c0d_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/WzyNoEmo/Desktop/hdmi_test_v3/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_24/bd_5c0d_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/WzyNoEmo/Desktop/hdmi_test_v3/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_25/bd_5c0d_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/WzyNoEmo/Desktop/hdmi_test_v3/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_17/bd_5c0d_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/WzyNoEmo/Desktop/hdmi_test_v3/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_18/bd_5c0d_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/WzyNoEmo/Desktop/hdmi_test_v3/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_19/bd_5c0d_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/WzyNoEmo/Desktop/hdmi_test_v3/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_11/bd_5c0d_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/WzyNoEmo/Desktop/hdmi_test_v3/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_12/bd_5c0d_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/WzyNoEmo/Desktop/hdmi_test_v3/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_2/bd_5c0d_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/WzyNoEmo/Desktop/hdmi_test_v3/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_3/bd_5c0d_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/WzyNoEmo/Desktop/hdmi_test_v3/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_4/bd_5c0d_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/WzyNoEmo/Desktop/hdmi_test_v3/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_5/bd_5c0d_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/WzyNoEmo/Desktop/hdmi_test_v3/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_6/bd_5c0d_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/WzyNoEmo/Desktop/hdmi_test_v3/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_1/bd_5c0d_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/WzyNoEmo/Desktop/hdmi_test_v3/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_1/bd_5c0d_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/WzyNoEmo/Desktop/hdmi_test_v3/hdmi_test.srcs/sources_1/bd/BD/ip/BD_axi_smc_0/ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/WzyNoEmo/Desktop/hdmi_test_v3/hdmi_test.srcs/sources_1/bd/BD/ip/BD_v_vid_in_axi4s_0_0/BD_v_vid_in_axi4s_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/WzyNoEmo/Desktop/hdmi_test_v3/hdmi_test.srcs/sources_1/bd/BD/ip/BD_v_vid_in_axi4s_0_0/BD_v_vid_in_axi4s_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/WzyNoEmo/Desktop/hdmi_test_v3/hdmi_test.srcs/sources_1/bd/BD/ip/BD_auto_pc_0/BD_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/WzyNoEmo/Desktop/hdmi_test_v3/hdmi_test.srcs/sources_1/bd/BD/BD_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/WzyNoEmo/Desktop/hdmi_test_v3/hdmi_test.srcs/constrs_1/new/constrs.xdc
set_property used_in_implementation false [get_files C:/Users/WzyNoEmo/Desktop/hdmi_test_v3/hdmi_test.srcs/constrs_1/new/constrs.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top BD_wrapper -part xc7z020clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef BD_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file BD_wrapper_utilization_synth.rpt -pb BD_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
