# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constrs.xdc

# Block Designs: bd/BD/BD.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD || ORIG_REF_NAME==BD} -quiet] -quiet

# IP: bd/BD/ip/BD_processing_system7_0_0/BD_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_processing_system7_0_0 || ORIG_REF_NAME==BD_processing_system7_0_0} -quiet] -quiet

# IP: bd/BD/ip/BD_clk_wiz_0_0/BD_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_clk_wiz_0_0 || ORIG_REF_NAME==BD_clk_wiz_0_0} -quiet] -quiet

# IP: bd/BD/ip/BD_rgb2dvi_0_0/BD_rgb2dvi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_rgb2dvi_0_0 || ORIG_REF_NAME==BD_rgb2dvi_0_0} -quiet] -quiet

# IP: bd/BD/ip/BD_rst_ps7_0_100M_0/BD_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_rst_ps7_0_100M_0 || ORIG_REF_NAME==BD_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/BD/ip/BD_breath_led_1_0/BD_breath_led_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_breath_led_1_0 || ORIG_REF_NAME==BD_breath_led_1_0} -quiet] -quiet

# IP: bd/BD/ip/BD_axi_vdma_0_0/BD_axi_vdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_axi_vdma_0_0 || ORIG_REF_NAME==BD_axi_vdma_0_0} -quiet] -quiet

# IP: bd/BD/ip/BD_axi_interconnect_1_0/BD_axi_interconnect_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_axi_interconnect_1_0 || ORIG_REF_NAME==BD_axi_interconnect_1_0} -quiet] -quiet

# IP: bd/BD/ip/BD_v_axi4s_vid_out_0_0/BD_v_axi4s_vid_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==BD_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: bd/BD/ip/BD_v_tc_0_0/BD_v_tc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_v_tc_0_0 || ORIG_REF_NAME==BD_v_tc_0_0} -quiet] -quiet

# IP: bd/BD/ip/BD_axi_smc_0/BD_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_axi_smc_0 || ORIG_REF_NAME==BD_axi_smc_0} -quiet] -quiet

# IP: bd/BD/ip/BD_util_vector_logic_0_0/BD_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_util_vector_logic_0_0 || ORIG_REF_NAME==BD_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/BD/ip/BD_v_vid_in_axi4s_0_0/BD_v_vid_in_axi4s_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_v_vid_in_axi4s_0_0 || ORIG_REF_NAME==BD_v_vid_in_axi4s_0_0} -quiet] -quiet

# IP: bd/BD/ip/BD_OV5640_0_0/BD_OV5640_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_OV5640_0_0 || ORIG_REF_NAME==BD_OV5640_0_0} -quiet] -quiet

# IP: bd/BD/ip/BD_auto_pc_0/BD_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_auto_pc_0 || ORIG_REF_NAME==BD_auto_pc_0} -quiet] -quiet

# XDC: bd/BD/BD_ooc.xdc
