#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2018.1 (64-bit)
#
# Filename    : BD.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Sun Dec 03 14:48:56 +0800 2023
# SW Build 2188600 on Wed Apr  4 18:40:38 MDT 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved. 
#
# usage: BD.sh [-help]
# usage: BD.sh [-lib_map_path]
# usage: BD.sh [-noclean_files]
# usage: BD.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'BD.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xil_defaultlib xpm axi_infrastructure_v1_1_0 smartconnect_v1_0 axi_protocol_checker_v2_0_2 axi_vip_v1_1_2 processing_system7_vip_v1_0_4 lib_cdc_v1_0_2 proc_sys_reset_v5_0_12 lib_pkg_v1_0_2 fifo_generator_v13_2_2 lib_fifo_v1_0_11 blk_mem_gen_v8_4_1 lib_bmg_v1_0_10 lib_srl_fifo_v1_0_2 axi_datamover_v5_1_18 axi_vdma_v6_3_4 axi_lite_ipif_v3_0_4 v_tc_v6_1_12 v_vid_in_axi4s_v4_0_8 v_axi4s_vid_out_v4_0_9 xlconstant_v1_1_4 util_vector_logic_v2_0_1 generic_baseblocks_v2_1_0 axi_data_fifo_v2_1_15 axi_register_slice_v2_1_16 axi_protocol_converter_v2_1_16)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "BD.sh - Script generated by export_simulation (Vivado v2018.1 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/b193/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/4903" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/a10f/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/cf48/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "D:/Xilinx/Vivado/2018.1/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "D:/Xilinx/Vivado/2018.1/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "D:/Xilinx/Vivado/2018.1/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "D:/Xilinx/Vivado/2018.1/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "D:/Xilinx/Vivado/2018.1/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "D:/Xilinx/Vivado/2018.1/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "D:/Xilinx/Vivado/2018.1/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "D:/Xilinx/Vivado/2018.1/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "D:/Xilinx/Vivado/2018.1/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/b193/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/4903" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/a10f/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/cf48/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "D:/Xilinx/Vivado/2018.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "D:/Xilinx/Vivado/2018.1/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "D:/Xilinx/Vivado/2018.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "D:/Xilinx/Vivado/2018.1/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/b193/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/4903" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/a10f/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/cf48/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/b193/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/4903" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/a10f/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/cf48/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/02c8/hdl/sc_util_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_checker_v2_0_2 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/b193/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/4903" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/a10f/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/cf48/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/3755/hdl/axi_protocol_checker_v2_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_2 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/b193/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/4903" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/a10f/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/cf48/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/725c/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work processing_system7_vip_v1_0_4 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/b193/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/4903" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/a10f/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/cf48/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/b193/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/b193/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/4903" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/a10f/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/cf48/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/BD/ip/BD_processing_system7_0_0/sim/BD_processing_system7_0_0.v" \
    "$ref_dir/../../../bd/BD/ip/BD_clk_wiz_0_0/BD_clk_wiz_0_0_clk_wiz.v" \
    "$ref_dir/../../../bd/BD/ip/BD_clk_wiz_0_0/BD_clk_wiz_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/d57c/src/ClockGen.vhd" \
    "$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/d57c/src/SyncAsync.vhd" \
    "$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/d57c/src/SyncAsyncReset.vhd" \
    "$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/d57c/src/DVI_Constants.vhd" \
    "$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/d57c/src/OutputSERDES.vhd" \
    "$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/d57c/src/TMDS_Encoder.vhd" \
    "$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/d57c/src/rgb2dvi.vhd" \
    "$ref_dir/../../../bd/BD/ip/BD_rgb2dvi_0_0/sim/BD_rgb2dvi_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_12 $vhdlan_opts \
    "$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/f86a/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/BD/ip/BD_rst_ps7_0_100M_0/sim/BD_rst_ps7_0_100M_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/b193/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/4903" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/a10f/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/cf48/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/BD/sim/BD.v" \
    "$ref_dir/../../../../../../Users/WzyNoEmo/Desktop/my_ip/breath_led/breath_led.srcs/sources_1/new/breath_led.v" \
    "$ref_dir/../../../bd/BD/ip/BD_breath_led_1_0/sim/BD_breath_led_1_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/b193/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/4903" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/a10f/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/cf48/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/7aff/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_2 $vhdlan_opts \
    "$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/7aff/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/b193/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/4903" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/a10f/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/cf48/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/7aff/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_fifo_v1_0_11 $vhdlan_opts \
    "$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/6078/hdl/lib_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work blk_mem_gen_v8_4_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/b193/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/4903" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/a10f/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/cf48/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/67d8/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_bmg_v1_0_10 $vhdlan_opts \
    "$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/9340/hdl/lib_bmg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_srl_fifo_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_datamover_v5_1_18 $vhdlan_opts \
    "$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/1150/hdl/axi_datamover_v5_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_vdma_v6_3_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/b193/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/4903" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/a10f/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/cf48/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/a10f/hdl/axi_vdma_v6_3_rfs.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_vdma_v6_3_4 $vhdlan_opts \
    "$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/a10f/hdl/axi_vdma_v6_3_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/BD/ip/BD_axi_vdma_0_0/sim/BD_axi_vdma_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/cced/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work v_tc_v6_1_12 $vhdlan_opts \
    "$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/6694/hdl/v_tc_v6_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work v_vid_in_axi4s_v4_0_8 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/b193/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/4903" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/a10f/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/cf48/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/d987/hdl/v_vid_in_axi4s_v4_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work v_axi4s_vid_out_v4_0_9 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/b193/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/4903" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/a10f/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/cf48/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/9a07/hdl/v_axi4s_vid_out_v4_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/b193/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/4903" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/a10f/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/cf48/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/BD/ip/BD_v_axi4s_vid_out_0_0/sim/BD_v_axi4s_vid_out_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/BD/ip/BD_v_tc_0_0/sim/BD_v_tc_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/b193/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/4903" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/a10f/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/cf48/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/BD/ip/BD_axi_smc_0/bd_0/sim/bd_5c0d.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/b193/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/4903" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/a10f/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/cf48/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/786b/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/b193/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/4903" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/a10f/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/cf48/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_10/sim/bd_5c0d_s00a2s_0.sv" \
    "$ref_dir/../../../bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_16/sim/bd_5c0d_s01a2s_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/b193/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/4903" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/a10f/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/cf48/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/92d2/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/b193/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/4903" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/a10f/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/cf48/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_20/sim/bd_5c0d_m00s2a_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/b193/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/4903" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/a10f/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/cf48/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/258c/hdl/sc_exit_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/b193/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/4903" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/a10f/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/cf48/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_26/sim/bd_5c0d_m00e_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/b193/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/4903" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/a10f/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/cf48/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/cf48/hdl/sc_node_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/b193/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/4903" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/a10f/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/cf48/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_21/sim/bd_5c0d_m00arn_0.sv" \
    "$ref_dir/../../../bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_22/sim/bd_5c0d_m00rn_0.sv" \
    "$ref_dir/../../../bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_23/sim/bd_5c0d_m00awn_0.sv" \
    "$ref_dir/../../../bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_24/sim/bd_5c0d_m00wn_0.sv" \
    "$ref_dir/../../../bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_25/sim/bd_5c0d_m00bn_0.sv" \
    "$ref_dir/../../../bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_17/sim/bd_5c0d_sawn_0.sv" \
    "$ref_dir/../../../bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_18/sim/bd_5c0d_swn_0.sv" \
    "$ref_dir/../../../bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_19/sim/bd_5c0d_sbn_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/b193/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/4903" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/a10f/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/cf48/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/8ad6/hdl/sc_mmu_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/b193/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/4903" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/a10f/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/cf48/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_13/sim/bd_5c0d_s01mmu_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/b193/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/4903" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/a10f/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/cf48/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/0f5f/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/b193/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/4903" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/a10f/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/cf48/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_14/sim/bd_5c0d_s01tr_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/b193/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/4903" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/a10f/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/cf48/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/925a/hdl/sc_si_converter_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/b193/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/4903" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/a10f/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/cf48/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_15/sim/bd_5c0d_s01sic_0.sv" \
    "$ref_dir/../../../bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_11/sim/bd_5c0d_sarn_0.sv" \
    "$ref_dir/../../../bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_12/sim/bd_5c0d_srn_0.sv" \
    "$ref_dir/../../../bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_7/sim/bd_5c0d_s00mmu_0.sv" \
    "$ref_dir/../../../bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_8/sim/bd_5c0d_s00tr_0.sv" \
    "$ref_dir/../../../bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_9/sim/bd_5c0d_s00sic_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/b193/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/4903" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/a10f/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/cf48/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/1b0c/hdl/sc_switchboard_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/b193/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/4903" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/a10f/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/cf48/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_2/sim/bd_5c0d_arsw_0.sv" \
    "$ref_dir/../../../bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_3/sim/bd_5c0d_rsw_0.sv" \
    "$ref_dir/../../../bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_4/sim/bd_5c0d_awsw_0.sv" \
    "$ref_dir/../../../bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_5/sim/bd_5c0d_wsw_0.sv" \
    "$ref_dir/../../../bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_6/sim/bd_5c0d_bsw_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconstant_v1_1_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/b193/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/4903" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/a10f/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/cf48/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/2fc9/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/b193/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/4903" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/a10f/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/cf48/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_0/sim/bd_5c0d_one_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_1/sim/bd_5c0d_psr_aclk_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/b193/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/4903" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/a10f/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/cf48/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/BD/ip/BD_axi_smc_0/sim/BD_axi_smc_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work util_vector_logic_v2_0_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/b193/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/4903" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/a10f/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/cf48/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/2137/hdl/util_vector_logic_v2_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/b193/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/4903" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/a10f/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/cf48/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/BD/ip/BD_util_vector_logic_0_0/sim/BD_util_vector_logic_0_0.v" \
    "$ref_dir/../../../bd/BD/ip/BD_v_vid_in_axi4s_0_0/sim/BD_v_vid_in_axi4s_0_0.v" \
    "$ref_dir/../../../bd/BD/ipshared/3a36/ov5640_driver.v" \
    "$ref_dir/../../../bd/BD/ipshared/3a36/cmos_reg_conf.v" \
    "$ref_dir/../../../bd/BD/ipshared/3a36/coms_data_convert.v" \
    "$ref_dir/../../../bd/BD/ipshared/3a36/iic_sccb.v" \
    "$ref_dir/../../../bd/BD/ip/BD_ov5640_driver_0_0/sim/BD_ov5640_driver_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/b193/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/4903" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/a10f/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/cf48/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_15 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/b193/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/4903" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/a10f/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/cf48/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/d114/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_16 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/b193/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/4903" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/a10f/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/cf48/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/0cde/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_converter_v2_1_16 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/b193/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/4903" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/a10f/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/cf48/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/1229/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/b193/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/4903" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/a10f/hdl" +incdir+"$ref_dir/../../../../hdmi_test.srcs/sources_1/bd/BD/ipshared/cf48/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/BD/ip/BD_auto_pc_0/sim/BD_auto_pc_0.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.BD xil_defaultlib.glbl -o BD_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./BD_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./BD.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key BD_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc BD_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./BD.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: BD.sh [-help]\n\
Usage: BD.sh [-lib_map_path]\n\
Usage: BD.sh [-reset_run]\n\
Usage: BD.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
